version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: looply-postgres
    environment:
      POSTGRES_DB: looply
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Demahum123!
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  postgres_data:
    driver: local